# -*- coding: utf-8 -*-
"""PRODIGY_CS_03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19LsTwbWZIKceyRFJLD5EKfxXyU2Cmd5K
"""

import re

def assess_password_strength(password):
    strength_score = 0
    length_criteria = 0
    uppercase_criteria = 0
    lowercase_criteria = 0
    number_criteria = 0
    special_criteria = 0

    if len(password) >= 8:
        length_criteria = 1
        strength_score += 1
    if len(password) >= 12:
        strength_score += 1

    if re.search(r'[A-Z]', password):
        uppercase_criteria = 1
        strength_score += 1

    if re.search(r'[a-z]', password):
        lowercase_criteria = 1
        strength_score += 1

    if re.search(r'\d', password):
        number_criteria = 1
        strength_score += 1

    if re.search(r'[!@#$%^&*(),.?":{}|<>]', password):
        special_criteria = 1
        strength_score += 1

    strength_levels = ['Very Weak', 'Weak', 'Moderate', 'Strong', 'Very Strong']
    if strength_score <= 1:
        strength = strength_levels[0]
    elif strength_score == 2:
        strength = strength_levels[1]
    elif strength_score == 3:
        strength = strength_levels[2]
    elif strength_score == 4:
        strength = strength_levels[3]
    else:
        strength = strength_levels[4]

    feedback = []
    if not length_criteria:
        feedback.append("Increase the length to at least 8 characters.")
    if not uppercase_criteria:
        feedback.append("Add uppercase letters.")
    if not lowercase_criteria:
        feedback.append("Add lowercase letters.")
    if not number_criteria:
        feedback.append("Include numbers.")
    if not special_criteria:
        feedback.append("Include special characters.")

    return strength, feedback

password = input("Enter a password to assess its strength: ")
strength, feedback = assess_password_strength(password)
print(f"Password Strength: {strength}")
if feedback:
    print("Feedback to improve your password:")
    for item in feedback:
        print(f" - {item}")